config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
    validates :name, presence: true
    validates :age, presence: true
    validates :cuteness, presence: true
    validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kittens }
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kitten }
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:notice] = 'Successfully created.'
      redirect_to @kitten
    else
      flash.now[:notice] = 'Invalid entry, please try again.'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:notice] = 'Successfully updated.'
      redirect_to @kitten
    else
      flash.now[:notice] = 'Invalid entry, please try again.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:notice] = 'Successfully deleted.'
    redirect_to root_path, status: :see_other
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.number_field :age, in: 1..40 %>
  </div>

  <div>
    <%= form.label :cuteness %><br>
    <%= form.number_field :cuteness, in: 1..10 %>
  </div>

  <div>
    <%= form.label :softness %><br>
    <%= form.number_field :softness, in: 1..10 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
<% end %>
<%= render 'form', kitten: @kitten %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
<% end %>
<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten %>
      <%= link_to "Delete", kitten_path(kitten),
    data: {
        turbo_method: :delete,
        turbo_confirm: 'Are you sure?'
    } %>
    </li>
  <% end %>
</ul>


<%= link_to "New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
<% end %>
<%= render 'form', kitten: @kitten %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
<% end %>

<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<ul>
  <li><%= link_to "Edit", edit_kitten_path(@kitten) %></li>
  <li><%= link_to "Destroy", kitten_path(@kitten),
    data: {
        turbo_method: :delete,
        turbo_confirm: 'Are you sure?'
    } %></li>
  <li><%= link_to 'Back to Index', root_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>